delete from BookActivity
delete from ChapterActivity
delete from CommentActivity
delete from Activity
delete from Comment
delete from Publication
delete from BookAuthor
delete from Chapter
delete from Book
delete from User
delete from CommentLabel
